"base_title" = "pyMoTH"
"base_tagline" = "Python static site generator with TOML/HTML/Markdown"
"base_description" = "The parser and static site generator that was made for Markdown format with TOML/HTML hybrid annotation and written in Python"
"base_url" = "https://xn--2os22eixx6na.xn--kpry57d/pyMoTH"
"base_year" = "2022"
"author_name" = "DJ Tratoh"
"author_url" = "https://sotong.cloud/@sotongdj"
"author_email" = "mail@stdj.me"
"paginate_number" = 5
"paginate_format" = "/p{num}/"
"separator_preview" = "<!--excerpt-->"
